source 'http://rubygems.org'
gem 'rails', '3.2.11'
gem 'rack'
gem 'therubyracer'
gem 'rake', "~> 10.0.3"
gem 'timezone'
gem 'builder'
gem 'capistrano'
gem 'pg'
gem 'thin'
gem 'execjs'
gem 'i18n', '~> 0.6.0'
gem 'multi_json', '~> 1.1.0'
gem 'httpclient', '~> 2.2.5'
gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'
gem 'jquery-rails'
gem 'rack-mini-profiler'
gem 'unicorn'
gem 'carrierwave'
gem 'rmagick'
gem 'raphael-rails'
gem 'exception_notification'
gem 'possessive'
gem 'savon', '~> 2.0'
gem 'less-rails'
gem 'rb-readline'
gem 'capistrano-rbenv'
gem 'capistrano-ext'
